#tomacat端口，访问地址设置
server:
  port: 8686
  servlet:
    context-path: /adm

#数据库访问连接，mybatis设置
jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/admanage?useUnicode=true&characterEncoding=utf8&userSSL=false
  user: root
  password: 123

mybatis_config_filePath: mybatis-config.xml
mapper_path: /mapper/**.xml
entity_package: com.example.admanage.entity

#热部署设置
spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#thymeleaf模板引用
  thymeleaf:
    cache: false
    prefix: classPath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

#freemarker模板引用
  freemarker:
    template-loader-path: classPath:/templates
    cache: false
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl


#静态js,css访问默认路径
  mvc:
    static-path-pattern: /static/**

logging:
  config: classpath:logback-spring.xml